
# Accessing Data within Pandas - Lab

## Introduction

In this lab, we'll look at a data set which contains information World cup matches. Let's use the pandas commands learned in the previous lecture to learn more about our data!

## Objectives
You will be able to:
* Understand and explain some key Pandas methods
* Access DataFrame data by using the label
* Perform boolean indexing on both Series and DataFrames
* Use simple selectors for series
* Set new Series and DataFrame inputs

## Load the data

Load the file `WorldCupMatches.csv` as a dataframe in Pandas

In [2]:
import pandas as pd
df = pd.read_csv("WorldCupMatches.csv")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
Year                    852 non-null float64
Datetime                852 non-null object
Stage                   852 non-null object
Stadium                 852 non-null object
City                    852 non-null object
Home Team Name          852 non-null object
Home Team Goals         852 non-null float64
Away Team Goals         852 non-null float64
Away Team Name          852 non-null object
Win conditions          852 non-null object
Attendance              850 non-null float64
Half-time Home Goals    852 non-null float64
Half-time Away Goals    852 non-null float64
Referee                 852 non-null object
Assistant 1             852 non-null object
Assistant 2             852 non-null object
RoundID                 852 non-null float64
MatchID                 852 non-null float64
Home Team Initials      852 non-null object
Away Team Initials      852 non-null object
dtypes: float64(8), object(12)
memory usage: 714.5+ KB

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

## Common methods and attributes

Use the correct method to look at the first 7 rows of the data set.

In [2]:
df.head(7)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
5,1930.0,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3.0,0.0,Mexico,,9249.0,1.0,0.0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201.0,1095.0,CHI,MEX
6,1930.0,17 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,4.0,0.0,Bolivia,,18306.0,0.0,0.0,MATEUCCI Francisco (URU),LOMBARDI Domingo (URU),WARNKEN Alberto (CHI),201.0,1092.0,YUG,BOL

Look at the last 3 rows of the data set.

In [9]:
df.tail(13)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
4559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4564,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Get a concise summary of your data using `.info()`

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
Year                    852 non-null float64
Datetime                852 non-null object
Stage                   852 non-null object
Stadium                 852 non-null object
City                    852 non-null object
Home Team Name          852 non-null object
Home Team Goals         852 non-null float64
Away Team Goals         852 non-null float64
Away Team Name          852 non-null object
Win conditions          852 non-null object
Attendance              850 non-null float64
Half-time Home Goals    852 non-null float64
Half-time Away Goals    852 non-null float64
Referee                 852 non-null object
Assistant 1             852 non-null object
Assistant 2             852 non-null object
RoundID                 852 non-null float64
MatchID                 852 non-null float64
Home Team Initials      852 non-null object
Away Team Initials      852 non-null object
dtypes: float64(8), object(12)
memory usage: 714.5+ KB

Obtain a tuple representing the number of rows and number of columns

In [7]:
df.shape

(4572, 20)

Use the appropriate attribute to get the column names

In [8]:
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

## Selecting dataframe information

When looking at the dataframe's `.head()`, you might have noticed that the games are structured chronologically in the dataframe.

Use the right selection method to print all the information from the 3rd to the 5th game.

In [12]:
print(df[2:5])

     Year              Datetime    Stage         Stadium         City  \
2  1930.0  14 Jul 1930 - 12:45   Group 2  Parque Central  Montevideo
3  1930.0  14 Jul 1930 - 14:50   Group 3         Pocitos  Montevideo
4  1930.0  15 Jul 1930 - 16:00   Group 1  Parque Central  Montevideo

  Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
2     Yugoslavia              2.0              1.0         Brazil
3        Romania              3.0              1.0           Peru
4      Argentina              1.0              0.0         France

  Win conditions  Attendance  Half-time Home Goals  Half-time Away Goals  \
2                    24059.0                   2.0                   0.0
3                     2549.0                   1.0                   0.0
4                    23409.0                   0.0                   0.0

                 Referee              Assistant 1                 Assistant 2  \
2    TEJADA Anibal (URU)  VALLARINO Ricardo (URU)         BALWAY Thomas (FRA)
3  WARNKEN Alberto (CHI)      LANGENUS Jean (BEL)    MATEUCCI Francisco (URU)
4    REGO Gilberto (BRA)     SAUCEDO Ulises (BOL)  RADULESCU Constantin (ROU)

   RoundID  MatchID Home Team Initials Away Team Initials
2    201.0   1093.0                YUG                BRA
3    201.0   1098.0                ROU                PER
4    201.0   1085.0                ARG                FRA

Now, print all the info from game 5-9, but we're only interested to print out the "Home Team Name" and the "Away Team Name",

In [31]:
print(df.loc[5:9,['Home Team Name','Away Team Name']])

  Home Team Name Away Team Name
5          Chile         Mexico
6     Yugoslavia        Bolivia
7            USA       Paraguay
8        Uruguay           Peru
9          Chile         France

Next, we'd like the information on all the games played in Group 3 for the 1950 World Cup.

In [34]:
print(df.loc[(df['Year']==1950) & (df['Stage']=='Group 3')])

      Year              Datetime    Stage           Stadium        City  \
56  1950.0  25 Jun 1950 - 15:00   Group 3          Pacaembu  Sao Paulo
61  1950.0  29 Jun 1950 - 15:30   Group 3  Durival de Brito   Curitiba
65  1950.0  02 Jul 1950 - 15:00   Group 3          Pacaembu  Sao Paulo

   Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
56         Sweden              3.0              2.0          Italy
61         Sweden              2.0              2.0       Paraguay
65          Italy              2.0              0.0       Paraguay

   Win conditions  Attendance  Half-time Home Goals  Half-time Away Goals  \
56                    36502.0                   2.0                   1.0
61                     7903.0                   2.0                   1.0
65                    25811.0                   1.0                   0.0

                  Referee             Assistant 1                Assistant 2  \
56        LUTZ Jean (SUI)     BERANEK Alois (AUT)        TEJADA Carlos (MEX)
61  MITCHELL Robert (SCO)       LEMESIC Leo (YUG)     GARCIA Prudencio (USA)
65     ELLIS Arthur (ENG)  GARCIA Prudencio (USA)  DE LA SALLE Charles (FRA)

    RoundID  MatchID Home Team Initials Away Team Initials
56    208.0   1219.0                SWE                ITA
61    208.0   1228.0                SWE                PAR
65    208.0   1218.0                ITA                PAR

Let's repeat the command above, but now we only want to print out the attendance colum for the Group 3 games

You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

In [3]:
print(df.loc[(df['Year']==1950)&(df['Stage']=='Group 3'),"Attendance"])

56    36502.0
61     7903.0
65    25811.0
Name: Attendance, dtype: float64

Throughout the entire history of the world cup, How many Home games were played by the Netherlands?

In [13]:
print(len(df.loc[df['Home Team Name'] == 'Netherlands']))

32

How many games were playes by the Netherlands in total?

In [15]:
print(len(df.loc[(df['Home Team Name'] == 'Netherlands') | (df['Away Team Name'] == 'Netherlands')]))

54

Next, let's try and figure out how many games the USA played in the 2014 world cup.

In [22]:

print(len(df[((df['Home Team Name'] == 'USA') | (df['Away Team Name'] == 'USA')) & (df['Year'] == 2014)]))

5

Now, let's try to find out how many countries participated in the 1986 world cup.

Hint 1: as a first step, create a new data set that only contain games in that year.

Hint 2: You can use `.unique()` to make sure you don't end up with duplicate country names.

In [23]:
dfy = df[df['Year']==1986]
print(dfy)
pinr

       Year              Datetime                  Stage  \
360  1986.0  31 May 1986 - 12:00                 Group A
361  1986.0  01 Jun 1986 - 16:00                 Group C
362  1986.0  01 Jun 1986 - 12:00                 Group D
363  1986.0  02 Jun 1986 - 12:00                 Group C
364  1986.0  02 Jun 1986 - 12:00                 Group A
365  1986.0  02 Jun 1986 - 16:00                 Group F
366  1986.0  03 Jun 1986 - 12:00                 Group D
367  1986.0  03 Jun 1986 - 12:00                 Group B
368  1986.0  03 Jun 1986 - 16:00                 Group F
369  1986.0  04 Jun 1986 - 12:00                 Group B
370  1986.0  04 Jun 1986 - 16:00                 Group E
371  1986.0  04 Jun 1986 - 12:00                 Group E
372  1986.0  05 Jun 1986 - 12:00                 Group A
373  1986.0  05 Jun 1986 - 12:00                 Group C
374  1986.0  05 Jun 1986 - 16:00                 Group A
375  1986.0  06 Jun 1986 - 12:00                 Group C
376  1986.0  06 Jun 1986 - 12:00                 Group D
377  1986.0  06 Jun 1986 - 16:00                 Group F
378  1986.0  07 Jun 1986 - 12:00                 Group D
379  1986.0  07 Jun 1986 - 12:00                 Group B
380  1986.0  07 Jun 1986 - 16:00                 Group F
381  1986.0  08 Jun 1986 - 12:00                 Group B
382  1986.0  08 Jun 1986 - 16:00                 Group E
383  1986.0  08 Jun 1986 - 12:00                 Group E
384  1986.0  09 Jun 1986 - 12:00                 Group C
385  1986.0  09 Jun 1986 - 12:00                 Group C
386  1986.0  10 Jun 1986 - 12:00                 Group A
387  1986.0  10 Jun 1986 - 12:00                 Group A
388  1986.0  11 Jun 1986 - 12:00                 Group B
389  1986.0  11 Jun 1986 - 12:00                 Group B
390  1986.0  11 Jun 1986 - 16:00                 Group F
391  1986.0  11 Jun 1986 - 16:00                 Group F
392  1986.0  12 Jun 1986 - 12:00                 Group D
393  1986.0  12 Jun 1986 - 12:00                 Group D
394  1986.0  13 Jun 1986 - 12:00                 Group E
395  1986.0  13 Jun 1986 - 12:00                 Group E
396  1986.0  15 Jun 1986 - 16:00             Round of 16
397  1986.0  15 Jun 1986 - 12:00             Round of 16
398  1986.0  16 Jun 1986 - 16:00             Round of 16
399  1986.0  16 Jun 1986 - 12:00             Round of 16
400  1986.0  17 Jun 1986 - 12:00             Round of 16
401  1986.0  17 Jun 1986 - 16:00             Round of 16
402  1986.0  18 Jun 1986 - 12:00             Round of 16
403  1986.0  18 Jun 1986 - 16:00             Round of 16
404  1986.0  21 Jun 1986 - 12:00          Quarter-finals
405  1986.0  21 Jun 1986 - 16:00          Quarter-finals
406  1986.0  22 Jun 1986 - 16:00          Quarter-finals
407  1986.0  22 Jun 1986 - 12:00          Quarter-finals
408  1986.0  25 Jun 1986 - 12:00             Semi-finals
409  1986.0  25 Jun 1986 - 16:00             Semi-finals
410  1986.0  28 Jun 1986 - 12:00   Match for third place
411  1986.0  29 Jun 1986 - 12:00                   Final

                              Stadium             City    Home Team Name  \
360                    Estadio Azteca     Mexico City           Bulgaria
361           Nou Camp - Estadio Le�n            Leon             Canada
362                           Jalisco     Guadalajara              Spain
363                  Estadio Irapuato        Irapuato       Soviet Union
364    Estadio Ol�mpico Universitario     Mexico City          Argentina
365             Estadio Universitario       Monterrey            Morocco
366                     Tres de Marzo     Guadalajara            Algeria
367                    Estadio Azteca     Mexico City            Belgium
368                       Tecnologico       Monterrey           Portugal
369  Bombonera - Estadio Nemesio Diez          Toluca           Paraguay
370                              Neza  Nezahualcoyotl           Scotland
371               Estadio Corregidora       Queretaro            Uruguay
372                        Cuauhtemoc          Puebla              Italy
373           Nou Camp - Estadio Le�n            Leon             France
374    Estadio Ol�mpico Universitario     Mexico City     Korea Republic
375                  Estadio Irapuato        Irapuato            Hungary
376                           Jalisco     Guadalajara             Brazil
377                       Tecnologico       Monterrey            England
378                     Tres de Marzo     Guadalajara   Northern Ireland
379                    Estadio Azteca     Mexico City             Mexico
380             Estadio Universitario       Monterrey             Poland
381  Bombonera - Estadio Nemesio Diez          Toluca               Iraq
382                              Neza  Nezahualcoyotl            Denmark
383               Estadio Corregidora       Queretaro         Germany FR
384           Nou Camp - Estadio Le�n            Leon            Hungary
385                  Estadio Irapuato        Irapuato       Soviet Union
386                        Cuauhtemoc          Puebla     Korea Republic
387    Estadio Ol�mpico Universitario     Mexico City          Argentina
388  Bombonera - Estadio Nemesio Diez          Toluca           Paraguay
389                    Estadio Azteca     Mexico City               Iraq
390                     Tres de Marzo     Guadalajara           Portugal
391                       Tecnologico       Monterrey            England
392                           Jalisco     Guadalajara   Northern Ireland
393                       Tecnologico       Monterrey            Algeria
394                              Neza  Nezahualcoyotl           Scotland
395               Estadio Corregidora       Queretaro            Denmark
396           Nou Camp - Estadio Le�n            Leon       Soviet Union
397                    Estadio Azteca     Mexico City             Mexico
398                        Cuauhtemoc          Puebla          Argentina
399                           Jalisco     Guadalajara             Brazil
400    Estadio Ol�mpico Universitario     Mexico City              Italy
401             Estadio Universitario       Monterrey            Morocco
402                    Estadio Azteca     Mexico City            England
403               Estadio Corregidora       Queretaro            Denmark
404                           Jalisco     Guadalajara             Brazil
405             Estadio Universitario       Monterrey         Germany FR
406                        Cuauhtemoc          Puebla              Spain
407                    Estadio Azteca     Mexico City          Argentina
408                           Jalisco     Guadalajara             France
409                    Estadio Azteca     Mexico City          Argentina
410                        Cuauhtemoc          Puebla             France
411                    Estadio Azteca     Mexico City          Argentina

     Home Team Goals  Away Team Goals    Away Team Name  \
360              1.0              1.0             Italy
361              0.0              1.0            France
362              0.0              1.0            Brazil
363              6.0              0.0           Hungary
364              3.0              1.0    Korea Republic
365              0.0              0.0            Poland
366              1.0              1.0  Northern Ireland
367              1.0              2.0            Mexico
368              1.0              0.0           England
369              1.0              0.0              Iraq
370              0.0              1.0           Denmark
371              1.0              1.0        Germany FR
372              1.0              1.0         Argentina
373              1.0              1.0      Soviet Union
374              1.0              1.0          Bulgaria
375              2.0              0.0            Canada
376              1.0              0.0           Algeria
377              0.0              0.0           Morocco
378              1.0              2.0             Spain
379              1.0              1.0          Paraguay
380              1.0              0.0          Portugal
381              1.0              2.0           Belgium
382              6.0              1.0           Uruguay
383              2.0              1.0          Scotland
384              0.0              3.0            France
385              2.0              0.0            Canada
386              2.0              3.0             Italy
387              2.0              0.0          Bulgaria
388              2.0              2.0           Belgium
389              0.0              1.0            Mexico
390              1.0              3.0           Morocco
391              3.0              0.0            Poland
392              0.0              3.0            Brazil
393              0.0              3.0             Spain
394              0.0              0.0           Uruguay
395              2.0              0.0        Germany FR
396              3.0              4.0           Belgium
397              2.0              0.0          Bulgaria
398              1.0              0.0           Uruguay
399              4.0              0.0            Poland
400              0.0              2.0            France
401              0.0              1.0        Germany FR
402              3.0              0.0          Paraguay
403              1.0              5.0             Spain
404              1.0              1.0            France
405              0.0              0.0            Mexico
406              1.0              1.0           Belgium
407              2.0              1.0           England
408              0.0              2.0        Germany FR
409              2.0              0.0           Belgium
410              4.0              2.0           Belgium
411              3.0              2.0        Germany FR

                           Win conditions  Attendance  Half-time Home Goals  \
360                                           96000.0                   0.0
361                                           65500.0                   0.0
362                                           35748.0                   0.0
363                                           16500.0                   3.0
364                                           60000.0                   2.0
365                                           19900.0                   0.0
366                                           22000.0                   0.0
367                                          110000.0                   1.0
368                                           23000.0                   0.0
369                                           24000.0                   1.0
370                                           18000.0                   0.0
371                                           30500.0                   1.0
372                                           32000.0                   1.0
373                                           36540.0                   0.0
374                                           45000.0                   0.0
375                                           13800.0                   1.0
376                                           48000.0                   0.0
377                                           20200.0                   0.0
378                                           28000.0                   0.0
379                                          114600.0                   1.0
380                                           19915.0                   0.0
381                                           20000.0                   0.0
382                                           26500.0                   2.0
383                                           30000.0                   1.0
384                                           31420.0                   0.0
385                                           14200.0                   0.0
386                                           20000.0                   0.0
387                                           65000.0                   1.0
388                                           16000.0                   0.0
389                                          103763.0                   0.0
390                                           28000.0                   0.0
391                                           22700.0                   3.0
392                                           51000.0                   0.0
393                                           23980.0                   0.0
394                                           20000.0                   0.0
395                                           36000.0                   1.0
396         Belgium win after extra time      32277.0                   0.0
397                                          114580.0                   1.0
398                                           26000.0                   1.0
399                                           45000.0                   1.0
400                                           70000.0                   0.0
401                                           19800.0                   0.0
402                                           98728.0                   1.0
403                                           38500.0                   1.0
404      France win on penalties (3 - 4)      65000.0                   0.0
405  Germany FR win on penalties (4 - 1)      41700.0                   0.0
406     Belgium win on penalties (4 - 5)      45000.0                   0.0
407                                          114580.0                   0.0
408                                           45000.0                   0.0
409                                          114500.0                   0.0
410          France win after extra time      21000.0                   0.0
411                                          114600.0                   1.0

     Half-time Away Goals                             Referee  \
360                   1.0              FREDRIKSSON Erik (SWE)
361                   0.0             SILVA ARCE Hernan (CHI)
362                   0.0         BAMBRIDGE Christopher (AUS)
363                   0.0                 AGNOLIN Luigi (ITA)
364                   0.0    SANCHEZ ARMINIO Victoriano (ESP)
365                   0.0      MARTINEZ BAZAN Jose Luis (URU)
366                   1.0                BUTENKO Valeri (RUS)
367                   2.0               ESPOSITO Carlos (ARG)
368                   0.0                   ROTH Volker (GER)
369                   0.0            PICON-ACKONG Edwin (MRI)
370                   0.0                  NEMETH Lajos (HUN)
371                   0.0              CHRISTOV Vojtech (TCH)
372                   1.0                    KEIZER Jan (NED)
373                   0.0          ARPPI FILHO Romualdo (BRA)
374                   1.0       AL SHANAR Fallaj Khuzam (KSA)
375                   0.0               AL SHARIF Jamal (SYR)
376                   0.0          MENDEZ MOLINA Romulo (GUA)
377                   0.0          GONZALEZ ROA Gabriel (PAR)
378                   2.0               BRUMMEIER Horst (AUT)
379                   0.0               COURTNEY George (ENG)
380                   0.0                 BENNACEUR Ali (TUN)
381                   2.0            DIAZ PALACIO Jesus (COL)
382                   1.0       MARQUEZ RAMIREZ Antonio (MEX)
383                   1.0                     IGNA Ioan (ROU)
384                   1.0  SILVA VALENTE Carlos Alberto (POR)
385                   0.0                TRAORE Idrissa (MLI)
386                   1.0                   SOCHA David (USA)
387                   0.0            ULLOA MORERA Berny (CRC)
388                   1.0                DOTCHEV Bogdan (BUL)
389                   0.0                PETROVIC Zoran (SRB)
390                   2.0                   SNODDY Alan (NIR)
391                   0.0                   DAINA Andre (SUI)
392                   2.0            KIRSCHEN Siegfried (GER)
393                   1.0                 TAKADA Shizuo (JPN)
394                   0.0                  QUINIOU Joel (FRA)
395                   0.0                 PONNET Alexis (BEL)
396                   0.0              FREDRIKSSON Erik (SWE)
397                   0.0          ARPPI FILHO Romualdo (BRA)
398                   0.0                 AGNOLIN Luigi (ITA)
399                   0.0                   ROTH Volker (GER)
400                   1.0               ESPOSITO Carlos (ARG)
401                   0.0                PETROVIC Zoran (SRB)
402                   0.0               AL SHARIF Jamal (SYR)
403                   1.0                    KEIZER Jan (NED)
404                   0.0                     IGNA Ioan (ROU)
405                   0.0            DIAZ PALACIO Jesus (COL)
406                   0.0            KIRSCHEN Siegfried (GER)
407                   0.0                 BENNACEUR Ali (TUN)
408                   1.0                 AGNOLIN Luigi (ITA)
409                   0.0       MARQUEZ RAMIREZ Antonio (MEX)
410                   0.0               COURTNEY George (ENG)
411                   0.0          ARPPI FILHO Romualdo (BRA)

                            Assistant 1                         Assistant 2  \
360        CODESAL MENDEZ Edgardo (MEX)                   ROTH Volker (GER)
361          MENDEZ MOLINA Romulo (GUA)            ULLOA MORERA Berny (CRC)
362                   SOCHA David (USA)                    KEIZER Jan (NED)
363               COURTNEY George (ENG)               BRUMMEIER Horst (AUT)
364          GONZALEZ ROA Gabriel (PAR)            DIAZ PALACIO Jesus (COL)
365                  QUINIOU Joel (FRA)                TRAORE Idrissa (MLI)
366                   DAINA Andre (SUI)                PETROVIC Zoran (SRB)
367  SILVA VALENTE Carlos Alberto (POR)          MENDEZ MOLINA Romulo (GUA)
368                DOTCHEV Bogdan (BUL)               AL SHARIF Jamal (SYR)
369            ULLOA MORERA Berny (CRC)                   SOCHA David (USA)
370            KIRSCHEN Siegfried (GER)       AL SHANAR Fallaj Khuzam (KSA)
371             SILVA ARCE Hernan (CHI)  SILVA VALENTE Carlos Alberto (POR)
372       MARQUEZ RAMIREZ Antonio (MEX)                   SNODDY Alan (NIR)
373    SANCHEZ ARMINIO Victoriano (ESP)                 TAKADA Shizuo (JPN)
374                     IGNA Ioan (ROU)                BUTENKO Valeri (RUS)
375                PETROVIC Zoran (SRB)         BAMBRIDGE Christopher (AUS)
376      MARTINEZ BAZAN Jose Luis (URU)                  QUINIOU Joel (FRA)
377               ESPOSITO Carlos (ARG)            KIRSCHEN Siegfried (GER)
378                 AGNOLIN Luigi (ITA)                  NEMETH Lajos (HUN)
379              FREDRIKSSON Erik (SWE)                     IGNA Ioan (ROU)
380            PICON-ACKONG Edwin (MRI)                 TAKADA Shizuo (JPN)
381              CHRISTOV Vojtech (TCH)    SANCHEZ ARMINIO Victoriano (ESP)
382                    KEIZER Jan (NED)          ARPPI FILHO Romualdo (BRA)
383                DOTCHEV Bogdan (BUL)                   SNODDY Alan (NIR)
384                 PONNET Alexis (BEL)                   DAINA Andre (SUI)
385       AL SHANAR Fallaj Khuzam (KSA)          GONZALEZ ROA Gabriel (PAR)
386                 URREA Joaquin (MEX)               AL SHARIF Jamal (SYR)
387          ARPPI FILHO Romualdo (BRA)      MARTINEZ BAZAN Jose Luis (URU)
388                 BENNACEUR Ali (TUN)             SILVA ARCE Hernan (CHI)
389                  NEMETH Lajos (HUN)                 AGNOLIN Luigi (ITA)
390                BUTENKO Valeri (RUS)                   ROTH Volker (GER)
391               BRUMMEIER Horst (AUT)              CHRISTOV Vojtech (TCH)
392                TRAORE Idrissa (MLI)               COURTNEY George (ENG)
393            PICON-ACKONG Edwin (MRI)               ESPOSITO Carlos (ARG)
394            DIAZ PALACIO Jesus (COL)                 BENNACEUR Ali (TUN)

In the world cup history, how matches had more than 5 goals in total?

## Changing values and creating new columns

With the information you currently have in your `df`, create a new column "Half-time Goals".

Run the code below. You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [ ]:
df.loc[df["Home Team Name"].str.contains('Korea'), "Home Team Name" ]

Imagine that for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

Make sure to verify your answer!